/*This file was generated by NativeWind. Do not edit!*/const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "Inter"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "textTransform": "none"
    },
    "textarea": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "[type='button']": {
      "backgroundColor": "transparent"
    },
    "[type='reset']": {
      "backgroundColor": "transparent"
    },
    "[type='submit']": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h2": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h3": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h4": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h5": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "flex-1": {
      "flexGrow": 1,
      "flexShrink": 1,
      "flexBasis": "0%"
    },
    "items-center": {
      "alignItems": "center"
    },
    "justify-center": {
      "justifyContent": "center"
    },
    "rounded": {
      "borderTopLeftRadius": 4,
      "borderTopRightRadius": 4,
      "borderBottomRightRadius": 4,
      "borderBottomLeftRadius": 4
    },
    "bg-gray-700": {
      "backgroundColor": "#27272A"
    },
    "py-4": {
      "paddingTop": 16,
      "paddingBottom": 16
    },
    "px-4": {
      "paddingLeft": 16,
      "paddingRight": 16
    },
    "font-sans": {
      "fontFamily": "Inter"
    },
    "font-bold": {
      "fontWeight": "700"
    },
    "text-lg": {
      "fontSize": 16
    },
    "text-xl": {
      "fontSize": 24
    },
    "text-xs": {
      "fontSize": 12
    },
    "text-sm": {
      "fontSize": 14
    },
    "w-full": {
      "width": "100%"
    },
    "ml-1": {
      "marginLeft": 4
    },
    "ml-4": {
      "marginLeft": 16
    },
    "mr-4": {
      "marginRight": 16
    },
    "m-4": {
      "marginTop": 16,
      "marginRight": 16,
      "marginBottom": 16,
      "marginLeft": 16
    },
    "w-5": {
      "width": 20
    },
    "bg-gray-800": {
      "backgroundColor": "#202024"
    },
    "w-52": {
      "width": 208
    },
    "w-72": {
      "width": 288
    },
    "color-blue-light": {
      "color": "#81D8F7"
    },
    "color-gray-400": {
      "color": "#7C7C8A"
    },
    "flex-row": {
      "flexDirection": "row"
    },
    "bg-gray-900": {
      "backgroundColor": "#121214"
    }
  }
});